site_name: My Docs
theme:
  name: material
  palette:
    primary: light green
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  search:
    lang: 'ja'
extra:
  generator: false

nav:
  - Home: index.md
  - Functions:
      - UDP: functions/udp.md
use_directory_urls: false

markdown_extensions:
  - pymdownx.details
  - mdx_truly_sane_lists:
      nested_indent: 2
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true