on:
  push:
    branches:
      - main
    paths:
      - documents/**

defaults:
  run:
    working-directory: documents

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mdx-truly-sane-lists
      - name: deploy
        run: mkdocs gh-deploy --force